[Instance.Tags]
scriptability = "Custom"
type = { Data = "BinaryString" }

[LocalizationTable.Contents]
scriptability = "Custom"
type = { Data = "String" }

[BasePart.CollisionGroups]
scriptability = "Custom"
type = { Data = "String" }

[BasePart.Size]
serialized_name = "size"

[BasePart.size]
canonical_name = "Size"
type = { Data = "Vector3" }

[Part.Shape]
serialized_name = "shape"

[Part.shape]
canonical_name = "Shape"
type = { Enum = "PartType" }

[FormFactorPart.FormFactor]
serialized_name = "formFactorRaw"

[FormFactorPart.formFactorRaw]
canonical_name = "FormFactor"
type = { Enum = "FormFactor" }

[Players.MaxPlayers]
serialized_name = "MaxPlayersInternal"

[Players.MaxPlayersInternal]
canonical_name = "MaxPlayers"

[Players.PreferredPlayers]
serialized_name = "PreferredPlayersInternal"

[Players.PreferredPlayersInternal]
canonical_name = "PreferredPlayers"

[Fire.Size]
serialized_name = "size_xml"

[Fire.size]
canonical_name = "Size"

[Fire.size_xml]
canonical_name = "Size"
type = { Data = "Float32" }

[Fire.Heat]
serialized_name = "heat_xml"

[Fire.heat_xml]
canonical_name = "Heat"
type = { Data = "Float32" }

[Smoke.Opacity]
serialized_name = "opacity_xml"

[Smoke.opacity_xml]
canonical_name = "Opacity"
type = { Data = "Float32" }

[Smoke.Size]
serialized_name = "size_xml"

[Smoke.size_xml]
canonical_name = "Size"
type = { Data = "Float32" }

[Smoke.RiseVelocity]
serialized_name = "riseVelocity_xml"

[Smoke.riseVelocity_xml]
canonical_name = "RiseVelocity"
type = { Data = "Float32" }