[Instance.Tags]
scriptability = "Custom"
type = { type = "Data", name = "BinaryString" }

[LocalizationTable.Contents]
scriptability = "Custom"
type = { type = "Data", name = "String" }

[BasePart.CollisionGroups]
scriptability = "Custom"
type = { type = "Data", name = "String" }

[BasePart.Size]
serialized_name = "size"

[BasePart.size]
canonical_name = "Size"

[BasePart.Shape]
serialized_name = "shape"

[BasePart.shape]
canonical_name = "Shape"

[BasePart.FormFactor]
serialized_name = "formFactorRaw"

[BasePart.formFactorRaw]
canonical_name = "FormFactor"
type = { type = "Enum", name = "FormFactor" }

[Players.MaxPlayers]
serialized_name = "MaxPlayersInternal"

[Players.MaxPlayersInternal]
canonical_name = "MaxPlayers"
type = { type = "Data", name = "Int32" }

[Players.PreferredPlayers]
serialized_name = "PreferredPlayersInternal"

[Players.PreferredPlayersInternal]
canonical_name = "PreferredPlayers"
type = { type = "Data", name = "Int32" }

[Fire.Size]
serialized_name = "size_xml"

[Fire.size]
canonical_name = "Size"

[Fire.size_xml]
canonical_name = "Size"
type = { type = "Data", name = "Float32" }

[Fire.Heat]
serialized_name = "heat_xml"

[Fire.heat_xml]
canonical_name = "Heat"
type = { type = "Data", name = "Float32" }

[Smoke.Opacity]
serialized_name = "opacity_xml"

[Smoke.opacity_xml]
canonical_name = "Opacity"
type = { type = "Data", name = "Float32" }

[Smoke.Size]
serialized_name = "size_xml"

[Smoke.size_xml]
canonical_name = "Size"
type = { type = "Data", name = "Float32" }

[Smoke.RiseVelocity]
serialized_name = "riseVelocity_xml"

[Smoke.riseVelocity_xml]
canonical_name = "RiseVelocity"
type = { type = "Data", name = "Float32" }