[add.Instance.Tags]
type = { Data = "BinaryString" }
scriptability = "Custom"

[add.LocalizationTable.Contents]
type = { Data = "String" }
scriptability = "Custom"

[add.BasePart.CollisionGroups]
type = { Data = "String" }
scriptability = "Custom"

[change.BasePart.Size]
serialized_name = "size"

[add.BasePart.size]
type = { Data = "Vector3" }
canonical_name = "Size"
scriptability = "None"

[change.Part.Shape]
serialized_name = "shape"

[add.Part.shape]
type = { Enum = "PartType" }
canonical_name = "Shape"
scriptability = "None"

[change.FormFactorPart.FormFactor]
serialized_name = "formFactorRaw"

[add.FormFactorPart.formFactorRaw]
type = { Enum = "FormFactor" }
canonical_name = "FormFactor"
scriptability = "None"

[change.Players.MaxPlayers]
serialized_name = "MaxPlayersInternal"

[change.Players.MaxPlayersInternal]
canonical_name = "MaxPlayers"

[change.Players.PreferredPlayers]
serialized_name = "PreferredPlayersInternal"

[change.Players.PreferredPlayersInternal]
canonical_name = "PreferredPlayers"

[change.Fire.Size]
serialized_name = "size_xml"

[change.Fire.size]
canonical_name = "Size"

[add.Fire.size_xml]
type = { Data = "Float32" }
canonical_name = "Size"
scriptability = "None"

[change.Fire.Heat]
serialized_name = "heat_xml"

[add.Fire.heat_xml]
type = { Data = "Float32" }
canonical_name = "Heat"
scriptability = "None"

[change.Smoke.Opacity]
serialized_name = "opacity_xml"

[add.Smoke.opacity_xml]
type = { Data = "Float32" }
canonical_name = "Opacity"
scriptability = "None"

[change.Smoke.Size]
serialized_name = "size_xml"

[add.Smoke.size_xml]
type = { Data = "Float32" }
canonical_name = "Size"
scriptability = "None"

[change.Smoke.RiseVelocity]
serialized_name = "riseVelocity_xml"

[add.Smoke.riseVelocity_xml]
type = { Data = "Float32" }
canonical_name = "RiseVelocity"
scriptability = "None"