# Body Movers are old objects that have a number of deprecated aliases.

[Change.BodyAngularVelocity.angularvelocity]
Kind = { Type = "Alias", AliasFor = "AngularVelocity" }

[Change.BodyAngularVelocity.maxTorque]
Kind = { Type = "Alias", AliasFor = "MaxTorque" }

[Change.BodyForce.force]
Kind = { Type = "Alias", AliasFor = "Force" }

[Change.BodyGyro.cframe]
Kind = { Type = "Alias", AliasFor = "CFrame" }

[Change.BodyGyro.maxTorque]
Kind = { Type = "Alias", AliasFor = "MaxTorque" }

[Change.BodyPosition.maxForce]
Kind = { Type = "Alias", AliasFor = "MaxForce" }

[Change.BodyPosition.position]
Kind = { Type = "Alias", AliasFor = "Position" }

[Change.BodyThrust.force]
Kind = { Type = "Alias", AliasFor = "Force" }

[Change.BodyThrust.location]
Kind = { Type = "Alias", AliasFor = "Location" }

[Change.BodyVelocity.maxForce]
Kind = { Type = "Alias", AliasFor = "MaxForce" }

[Change.BodyVelocity.velocity]
Kind = { Type = "Alias", AliasFor = "Velocity" }