# Fire.Size is serialized as size_xml. size is an alias of Size.
[Change.Fire.Size]
Kind = { Type = "Canonical", Serialization = { Type = "SerializesAs", Name = "size_xml" } }

[Change.Fire.size]
Kind = { Type = "Alias", AliasFor = "Size" }

[Add.Fire.size_xml]
Kind = { Type = "Alias", AliasFor = "Size" }
DataType = { Type = "Value", Name = "Float32" }
Scriptability = "None"

# Fire.Heat is serialized as heat_xml.
[Change.Fire.Heat]
Kind = { Type = "Canonical", Serialization = { Type = "SerializesAs", Name = "heat_xml" } }

[Add.Fire.heat_xml]
Kind = { Type = "Alias", AliasFor = "Heat" }
DataType = { Type = "Value", Name = "Float32" }
Scriptability = "None"

# Smoke.Opacity is serialized as opacity_xml.
[Change.Smoke.Opacity]
Kind = { Type = "Canonical", Serialization = { Type = "SerializesAs", Name = "opacity_xml" } }

[Add.Smoke.opacity_xml]
Kind = { Type = "Alias", AliasFor = "Opacity" }
DataType = { Type = "Value", Name = "Float32" }
Scriptability = "None"

# Smoke.Size is serialized as size_xml.
[Change.Smoke.Size]
Kind = { Type = "Canonical", Serialization = { Type = "SerializesAs", Name = "size_xml" } }

[Add.Smoke.size_xml]
Kind = { Type = "Alias", AliasFor = "Size" }
DataType = { Type = "Value", Name = "Float32" }
Scriptability = "None"

# Smoke.RiseVelocity is serialized as riseVelocity_xml.
[Change.Smoke.RiseVelocity]
Kind = { Type = "Canonical", Serialization = { Type = "SerializesAs", Name = "riseVelocity_xml" } }

[Add.Smoke.riseVelocity_xml]
Kind = { Type = "Alias", AliasFor = "RiseVelocity" }
DataType = { Type = "Value", Name = "Float32" }
Scriptability = "None"