# MaxPlayersInternal is the serialized form of MaxPlayers.
# It's also reflected to Lua with a high enough security level.
[Change.Players.MaxPlayers]
Kind = { Type = "Canonical", Serialization = { Type = "SerializesAs", Name = "MaxPlayersInternal" } }

[Change.Players.MaxPlayersInternal]
Kind = { Type = "Alias", AliasFor = "MaxPlayers" }

# PreferredPlayersInternal is the serialized form of PreferredPlayers.
# It's also reflected to Lua with a high enough security level.
[Change.Players.PreferredPlayers]
Kind = { Type = "Canonical", Serialization = { Type = "SerializesAs", Name = "PreferredPlayersInternal" } }

[Change.Players.PreferredPlayersInternal]
Kind = { Type = "Alias", AliasFor = "PreferredPlayers" }