[package]
name = "rbx_xml"
description = "Weakly-typed Roblox DOM implementation for Rust"
version = "0.12.0-alpha.4"
license = "MIT"
documentation = "https://docs.rs/rbx_xml"
homepage = "https://github.com/rojo-rbx/rbx-dom"
repository = "https://github.com/rojo-rbx/rbx-dom.git"
readme = "README.md"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"

[dependencies]
rbx_dom_weak = { version = "2.0.0-alpha.1", path = "../rbx_dom_weak" }
rbx_reflection = { version = "4.0.0-alpha.1", path = "../rbx_reflection" }
rbx_reflection_database = { version = "0.1.0", path = "../rbx_reflection_database" }

base64 = "0.11.0"
log = "0.4.6"
xml-rs = "0.8.0"

[dev-dependencies]
env_logger = "0.7.1"
insta = "0.16.0"
